[phases.setup]
nixPkgs = ['nodejs_20']

[phases.build]
cmds = [
    'cd ui-react && npm install && npm run build && cd ..'
]

[start]
cmd = 'gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120'
