[phases.setup]
nixPkgs = ['python311', 'nodejs_20', 'npm-9_x']

[phases.install]
cmds = [
    'pip install -r requirements.txt',
    'cd ui-react && npm install && cd ..'
]

[phases.build]
cmds = [
    'cd ui-react && npm run build && cd ..'
]

[start]
cmd = 'gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120'
