[phases.setup]
nixPkgs = ["python310", "nodejs-18_x"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "cd ui-react && npm install"
]

[phases.build]
cmds = [
  "cd ui-react && npm run build"
]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
