[build]
builder = "NIXPACKS"
buildCommand = "cd ui-react && npm install && npm run build && cd .."

[deploy]
startCommand = "gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
healthcheckPath = "/"
healthcheckTimeout = 100
